### ISSUE TITLE
vuepress 的 hmr 确实是有一些不稳定,会偶尔出现 无法成功更新的问题

### ISSUE THREAD

**Issue by HJrookie** [deniapps/vns#1]
搜解决方案的时候 搜到了 你的博客,首先为你的 `stock` 默哀 ` ~_~  `  
另外,通过清除.vuepress 文件夹下的  `.temp` 以及  `.cache` 文件 ,然后重新 `npm run dev ` 就好了

**Comment by HJrookie** [comment]
另外 你今天好像 没写日记  :joy:

**Comment by deniapps** [comment]
我最后好像是重启电脑搞定的
https://61dh.com/diary/#vuepress-hot-module-replacement
不过我就碰到一次，应该是@vuepress的bug吧？毕竟还是beta。如果下次再发生，我到他们家发个issue。

另外：多谢问候，哈哈！stock还行，我没有多少。痛心的是数字币啊！没办法，继续#HODL！
日记是按美国时间来，今天(19号)一定写。不过这才半个月，已经3天没记了，有点惭愧啊！
